dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request OR tag is present

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-cloudwatch-log-metric-filter
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-cloudwatch-log-metric-filter v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-cloudwatch-log-metric-filter/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: K7Ql7Hl2cw4tIIKwYQ/l/m7iZNDlFA6YKQpHynzT3b+A9TZH9sp9Q3LFDa/bU+tPZGU/kRT7sCIF/eBUpB/slRy1WehNTHOOPn85ArJGAwWsYtQ3pi5EIP9Z6yTNlgFz1TrF8Mj1d4EQg1uVHevbQnL5KIJ3vwA89Hd+m0Y7r9o14MDRg056hBQlnMmg4qzb2WRtnH7bf3oGAGOerBU75RPYhT7e+ujETkCuYGNBCicscyJhvE93WSyD46VUqYW4EybV1BbDhLB9+nb2WossAZBLit184uomj/9lHDvXyGY0Rn81ZfM/1/X1vB7Z9VOJLaAhd8qfeBzI12OVPeEGgzS1/sDvzNKX6zwuwgPxFzT1zdsPT1h7C1zbVOMBeiV5n+ZAqqR9CeijQJoWfx9gt0YrmvVnR/7QLzeQSf+tDH5Np6LBKuQigxUF2fJq6nK3NZ1oGj2t4NWdAAtmztuk9ofA84wvhaLVQD/UFH35iJXVkD3paVeu0aE4Ph2vu7Y5tXjo1ctWSCrM05vRMtd4Ljb/hfPu6Zclb4QuSWNexIARHKZswwrZxanqZRTWd/bYLz1Y66plgX1cxzdLTggv3BsuAa++lKTHtvMx+9METVtT3kHPD6lsYmTPoaZ2u3PUYaExDbqEgi3e0nq2OIa9VRt060tuedLa5/BLfCgOU18=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-cloudwatch-log-metric-filter
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
